config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  resources :store_locators
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
  resources :chatbot_steps
  
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  resources :posts
  resources :posts do
    resources :replies, only: [:index, :create]
  end
  resources :replies, only: [:edit, :show, :update]
  resources :chatbot_messages, except: [:edit, :update, :destroy]
  resources :reminders
  resources :user_plants, except: [:index]
  resources :users, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new do
    get '/', to: 'users#current_user_dashboard'
  end
  
  constraints Clearance::Constraints::SignedOut.new do
    get '/', to: redirect('/sign_in')
  end
end

app/models/reply.rb
class Reply < ApplicationRecord
    belongs_to :post
    belongs_to :user
    validates :body, presence: true

    after_commit :create_notifications, on: :create

    private

      def create_notifications
        Notification.create do |notification|
          notification.notify_type = 'post'
          notification.actor = self.user
          notification.user = User.find(self.post.user_id)
          notification.target = self
          notification.second_target = self.post
        end
      end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :require_login
  before_action :set_reply, only: %i[ show edit update destroy ]

  # GET /replies or /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1 or /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies or /replies.json
  def create
    @post = Post.find(params[:post_id])
    @reply = @post.replies.new(reply_params)

    respond_to do |format|
      if @reply.save
        format.html { redirect_to @post, notice: "Reply was successfully created." }
        format.json { render :show, status: :created, location: @reply }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1 or /replies/1.json
  def update
    @post = Post.find(reply_params[:post_id])
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @post, notice: "Reply was successfully updated." }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1 or /replies/1.json
  def destroy
    @reply.destroy
    @post = Post.find(params[:post_id])
    respond_to do |format|
      format.html { redirect_to @post, notice: "Reply was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reply_params
      params.require(:reply).permit(:user_id, :post_id, :body, :created_at)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_with(model: reply) do |form| %>
  <% if reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
        <% reply.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="height:55px;"> </div>


  <div class="field">
    <%= form.hidden_field :user_id, value: reply.user_id %>
  </div>

  <div class="field" >
    <%= form.hidden_field :post_id, value: reply.post_id %>
  </div>

  <div class="field" >
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="actions" >
    <%= form.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<div>
    <div class="row" style = "height: 330px;">
    <div class = "col-3"></div>
        <div class="col-md-6 bg-editL" style="height: 600px; background-color: green; border: 5px solid green; border-radius: 25px;">
        <div class = "row text-center" style = "height: 50px;"></div>
        <h1 class='text-center'  style="color:yellow;"> Editing Reply</h1>

        <%= render 'form', reply: @reply %>
        <%= link_to 'Back', Post.where(id: @reply.post_id).first, class: "mt-2 btn btn-warning"%>

        </div>
    </div>
</div>

<div style="height:355px;"> </div>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Replies</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Body</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.user_id %></td>
        <td><%= reply.post_id %></td>
        <td><%= reply.body %></td>
        <td><%= reply.created_at %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form', reply: @reply %>

<%= link_to 'Back', replies_path, class: "mt-2 btn btn-primary" %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reply.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @reply.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @reply.body %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @reply.created_at %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', reply_path, class: "mt-2 btn btn-primary" %>