config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  resources :store_locators
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
  resources :chatbot_steps
  
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  resources :posts
  resources :posts do
    resources :replies, only: [:index, :create]
  end
  resources :replies, only: [:edit, :show, :update]
  resources :chatbot_messages, except: [:edit, :update, :destroy]
  resources :reminders
  resources :user_plants, except: [:index]
  resources :users, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new do
    get '/', to: 'users#current_user_dashboard'
  end
  
  constraints Clearance::Constraints::SignedOut.new do
    get '/', to: redirect('/sign_in')
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic 
  include Clearance::User

    has_many :user_plants
    has_many :reminders
    has_many :chatbot_messages
    has_many :replies
    has_many :posts
    
    validates :username, presence: true
    validates :email, presence: true, uniqueness: true

end

app/controllers/users_controller.rb
require './lib/posts_utils'

class UsersController < Clearance::UsersController
  # before_action :require_login
  before_action :require_login, except: [:new, :create, :set_user, :user_params]
  before_action :set_user, only: %i[ show edit update destroy ]
  
  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @related_posts = PostsUtils.get_related_posts(UserPlant.where(user_id: current_user.id), 3)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def current_user_dashboard
    redirect_to current_user
  end
  
  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def trefle(plant)
    b = plant.plant_type
    a = PlantType.where(name: "Garden sorrel").first.trefle_id
    return b
  end


  def Humidity(plant)
    token = "2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y"
    type = plant.plant_type
    plants = JSON
            .parse(
              Net::HTTP.get(
                URI.parse(
                    "https://trefle.io/api/v1/plants/"  +  type +"?token=" + token
                    #https://trefle.io/api/v1/plants/165409?token=2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y
                )
              )
            )#['data'].reject{ |plant| plant['common_name'] == nil }
    humidity =  plants["data"]["main_species"]["growth"]["soil_humidity"]
    #Required humidity of the soil, on a scale from 0 (xerophile) to 10 (subaquatic)
    if(humidity.nil?) then
      return "0"
    end
    return "10"
  end


  def Precipitation(plant)
    token = "2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y"
    type = plant.plant_type
    plants = JSON
            .parse(
              Net::HTTP.get(
                URI.parse(
                    "https://trefle.io/api/v1/plants/"  +  type +"?token=" + token

                    #look up plant
                    #https://trefle.io/api/v1/plants/165409?token=2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y
                    
                    #filter plants to take out null values
                    #https://trefle.io/api/v1/plants?token=2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y&filter_not[soil_humidity]=null&page=1
                )
              )
            )#['data'].reject{ |plant| plant['common_name'] == nil }
    precip =  plants["data"]["main_species"]["growth"]["minimum_precipitation"]
    if(precip.nil?) then
      return "Unknown Precip"
    end
    return precip
  end

  def getPages(plant)
    token = "2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y"
    type = plant.plant_type
    plants = JSON
            .parse(
              Net::HTTP.get(
                URI.parse(
                    #"https://trefle.io/api/v1/plants/"  +  type +"?token=" + token
                    #https://trefle.io/api/v1/plants/165409?token=2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y
                    "https://trefle.io/api/v1/plants?token=" + token + "&filter_not[soil_humidity]=null"
                )
              )
            )#['data'].reject{ |plant| plant['common_name'] == nil }
    pages = plants["links"]["last"].split("=")
    return pages[pages.length()-1]
  end

  def commonNames_Page(plant, page)
    token = "2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y"
    type = plant.plant_type
    plants = JSON
            .parse(
              Net::HTTP.get(
                URI.parse(
                    #"https://trefle.io/api/v1/plants/"  +  type +"?token=" + token
                    #https://trefle.io/api/v1/plants/165409?token=2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y
                    "https://trefle.io/api/v1/plants?token=" + token + "&filter_not[soil_humidity]=null&page=" + page
                )
              )
            )#['data'].reject{ |plant| plant['common_name'] == nil }
    plantsOnPage =  plants["data"]
    names = []
    plantsOnPage.each do |currPlant|
      names.append(currPlant["common_name"])
    end
    return names
  end


  def commonNames(plant)
    numOfPages = getPages(plant).to_i
    names = []
    for i in 1..1
      names.concat(commonNames_Page(plant, i.to_s))
    end
    return names
  end











  def filterRain(plant)
    token = "2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y"
    type = plant.plant_type
    plants = JSON
            .parse(
              Net::HTTP.get(
                URI.parse(
                    #"https://trefle.io/api/v1/plants/"  +  type +"?token=" + token
                    #https://trefle.io/api/v1/plants/165409?token=2yGrEg0Qad9zb1rA5PRoYlsj2L1XNu13A6dC71t-c-Y
                    "https://trefle.io/api/v1/plants?token=" + token + "&filter_not[soil_humidity]=null"
                )
              )
            )#['data'].reject{ |plant| plant['common_name'] == nil }
    precip =  plants["data"].length()
    return plants["data"][0]
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      </div>
      <ul>
        <% user.errors.each do |error| %>
          <li class='text-danger'><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div>

    <div class="m-2 text-field" style="color:#9AE19D;">
      <%= form.label "Full Name" %>
      <%= form.text_field :username, class: 'mb-1 form-control'  %>
    </div>

    <div class="m-2 email-field" style="color:#9AE19D">
      <%= form.label :email %>
      <%= form.text_field :email, type: 'email', class: 'mb-1 form-control'  %>
    </div>

    <div class="m-2 password-field" style="color:#9AE19D;">
      <%= form.label :password %>
      <%= form.password_field :password, class: 'mb-1 form-control'  %>
    </div>

    <% if signed_in? %>
    
     <div class = "m-2 row"> 
        <div class = 'text-center'>
          <%= form.submit "Update Account", class: "mt-2 btn ", style: "background-color: #9AE19D" %>
        </div>
      </div>

    <% else%>

      <div class = "m-2 row" style="color: #9AE19D">
        <div class = 'text-center'>
          <%= form.submit "Create my account", class: "mt-2 btn", style:"background-color:#9AE19D" %>
        </div>
      </div>

    <%end%>

    <div class="m-2 mb-4 other-links">
      <%= link_to 'Back', sign_in_path, class: "mt-2 btn btn-dark", style: "color: white;" %>
    </div>

  </div>
  
<% end %>

app/views/users/edit.html.erb
<div class = "container bg-leaves" style = "height: 600px; border: 3px solid green; border-radius: 25px;">
    <div class = "row" style = "height: 50px;">
    </div>
    <div class = "row justify-content-center">
        <h1 class = "text-center" style = "color:white;">Update User Information</h1>
    </div>
    <div class = "container">

        <%= render 'form', user: @user %>

        <%#= link_to 'Back', current_user %>
    </div>
    <div class = "row" style = "100px;">
    </div>
</div>


<div style="height:900px;"> </div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<%# render 'index' - %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div >
  <div class="row" style = "height: 430px;">
    <div class = "col-3">
    </div>

    <div class="col-md-6 bg-leaves" style="height: 600px; background-color: green; border: 5px solid green; border-radius: 25px;">

      <div class = "row text-center" style = "height: 50px;">
      </div>

      <h1 class='text-center'  style="color:white;">Sign up</h1>

      <%= render 'form', user: @user -%>

    </div>
  </div>
</div>

<div style="height:555px;"> </div>

app/views/users/show.html.erb
<!DOCTYPE html>
<p id="notice"><%= notice %></p>

<div class="row" style = "height: 10px;"> </div>

<!-- Design inspired from https://www.hotjar.com/  template i randomly found-->
<div class="jumbotron bg-white leaf-background" style="box-shadow: 0px 10px 10px grey; border-radius: 70px; border: 3px solid green">
  <div class="container text-center text-lg-left">
    <div class="row">
      <div class="col-lg-8">
          <h1 class="display-4" style="text-align:center;">Welcome to the Garden, 
            <span class="highlight-word">
              <strong> <%= current_user.username %>!</strong> 
            </span>
          </h1>
          <div class = "row">

            <div class = "col">
              <div class = "row justify-content-center" style = "height: 50px; font-size: large;">
                <h5>Plants Owned: <span class = "badge badge-secondary"><%= current_user.user_plants.count%></span></h5>
              </div>
              <div class = "row justify-content-center" style = "height: 50px; font-size: large;">
                <h5>Water Reminders: <span class = "badge badge-secondary"><%= current_user.reminders.where(reminder_type: 0).count%></span></h5>
              </div>
            </div>

            <div class = "col">
              <div class = "row justify-content-center" style = "height: 50px; font-size: large;">
                <h5>Trim Reminders: <span class = "badge badge-secondary"><%= current_user.reminders.where(reminder_type: 1).count%></span></h5>
              </div>
              <div class = "row justify-content-center" style = "height: 50px;font-size: large;">
                <h5>Fertilizer Reminders: <span class = "badge badge-secondary"><%= current_user.reminders.where(reminder_type: 2).count%></span></h5>
              </div>
            </div>
          </div>

          <div class = "row justify-content-center">
            <span class="text-center d-inline-block">
              <%= button_to 'Have a question?', new_post_path, method: :get, class: "btn btn-lg w-100 text-light", style: "background-color: #537A5A;"%>
              <p class="text-muted">Have plant experts answer your questions on our forum.</p>
            </span>
          </div>  

          <div class = "row justify-content-center button-row-show" style="text-align: center;">
              <div class = "col-md-auto">
                <div class = "row">
                  <%= button_to new_user_plant_path, method: :get, class: "btn btn-secondary text-light space" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 20 20">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"></path>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
                  </svg> Add Plant
                  <% end %>
                  <%= button_to edit_user_path(@user), method: :get, class: "btn btn-secondary text-light space" do %>
                    Edit User Info
                  <% end %>

                  <%= button_to new_reminder_path, method: :get, class: "btn btn-secondary text-light space" do %>
                    Add Reminder
                  <% end %>

                  <%= button_to reminders_path, method: :get, class: "btn btn-secondary text-light space" do %>
                    All Reminders
                  <% end %>

                </div>
              </div>
            
          </div> 
          

        </div>
      <div class="col-lg-4 align-items-center d-flex" style="position: relative; border-radius: 50%;">
        <%= image_tag @user.gravatar_url(:email => @user.email), style: "border-radius: 50%;"%>
      </div>
    </div>
  </div>
</div>

  <div class = "row plant-item">
    <% if UserPlant.where(user_id: current_user.id.to_i).empty? %>
      <p>
        <strong> You dont have any plant yet, would you like to add some? </strong>
      </p>
    <% else %>
      <% UserPlant.where(user_id: current_user.id.to_i).each do |plant| %>

        <div class = "plant-item col-4 " >
          <div class="card text-center border-success mb-3" style="box-shadow: 0px 10px 10px grey; border-radius: 20px; ">
            <img class="card-img-top-center img-fluid min-width: 200px !important;" src=<%= "#{plant.img_url}" %>  alt="Picture for this plant" style= "height: 200px; object-fit: cover; border-radius: 20px 20px 0px 0px;">
            <div class="card-body" >
              <h4 class="card-title"> <%="#{plant.name}"%> </h4>
              <p class="card-text">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item">
                    <i class="fas fa-clock text-success mx-2"></i>
                    <%= "Age: #{plant.age}" %>
                  </li>
                  <li class="list-group-item">
                    <i class="fas fa-tree text-success mx-2"></i>
                    <%= "Type: #{PlantType.where(trefle_id: plant.plant_type).first.name}" %>
                  </li>
                  <li class="list-group-item">
                  <i class="fas fa-seedling text-success mx-2"></i>
                    <%= "Birth: #{plant.created_at}" %>
                  </li>
                </ul>    
                <div class = "row justify-content-center">
                  <div class = "box" style="overflow:hidden;">
                    <p>
                      <%= "Description: #{plant.description}" %>
                    <p>
                  </div>
                </div>
                <div class = "row"></div>
              </p>
              <a>
                <div>
                  <%= link_to 'Remove', plant, method: :delete, class: "text-light btn ", style:"background-color: #537A5A;", data: { confirm: 'Are you sure?' } %> 
                  <%= link_to 'Edit', edit_user_plant_path(plant), class: 'text-dark btn btn-warning'%>
                  <button type="button" class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="right" data-content= "<%= "#{plant.description}"%>">
                    <i class="fas fa-tree text-success mx-2"></i>
                  </button>
                </div>
                <!--Card hover class =  stretched-link -->
              </a>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<script>
  $(document).ready(function(){
    $('[data-toggle="popover"]').popover();   
  });
</script>


<script>
function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>

  <h2 style="padding: 10px;">Posts related to your plants:</h2>
  <% if @related_posts.empty?%>
    <h4 class="text-danger" style="text-align: right;">No related posts were found for any of your plants</h4>
  <% else %>
    <div class= "d-flex justify-content-center">
      <% @related_posts.each do |post| %>
        <div class="card mt-3 mx-3" style="box-shadow: 0px 4px 10px grey; background: white; width: 20rem; display: inline-block;">
          <div class="card-body">
            <h5 class="card-title"><%= link_to post.title.truncate(20, separator: ' '), post_path(post) %></h5>
            <p class="card-text font-weight-bold">
                <%= post.user.username %>
              | <%= time_ago_in_words post.created_at %> ago
              | <%= post.replies.length %> Replies
              <%= "| Edited" if post.edited?%>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<div class="row" style = "height: 350px;"></div>