config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  resources :store_locators
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
  resources :chatbot_steps
  
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  resources :posts
  resources :posts do
    resources :replies, only: [:index, :create]
  end
  resources :replies, only: [:edit, :show, :update]
  resources :chatbot_messages, except: [:edit, :update, :destroy]
  resources :reminders
  resources :user_plants, except: [:index]
  resources :users, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new do
    get '/', to: 'users#current_user_dashboard'
  end
  
  constraints Clearance::Constraints::SignedOut.new do
    get '/', to: redirect('/sign_in')
  end
end

app/models/post.rb
class Post < ApplicationRecord
  # Using gem active_record-events, allowing to update edited post

  
  has_event :edit
  
  has_many :replies
  belongs_to :user
  enum topics: [:bugs, :disease, :color, :watering, :sunlight, :soil_care, :buying_plants, :temperature]

  scope :ordered_by_newest, -> {order(created_at: :desc)}
  scope :ordered_by_oldest, -> {order(created_at: :asc)}
  scope :ordered_by_most_replies, -> {left_joins(:replies).group(:id).order('COUNT(replies.id) DESC')}
  scope :ordered_by_least_replies, -> {left_joins(:replies).group(:id).order('COUNT(replies.id) ASC')}
  
  validates :title, presence: true, length: { minimum: 1, maximum: 500 }
  validates :body, presence: true, length: { minimum: 1, maximum: 3500 }
  validates :topic, presence: true

  paginates_per 7
  
  def self.search(search)
    if search
      where(topic: search)
    else
      all
    end
  end
  
end

app/controllers/posts_controller.rb
require './lib/posts_utils'

class PostsController < ApplicationController
  before_action :require_login
  before_action :set_post, only: %i[ show edit update destroy ]
  
  # GET /posts or /posts.json
  def index
    @orders = PostsUtils::ORDERS
    @all_posts = Post.all
    @current_topic = params[:search]
    @current_order = params[:order] || @orders[0]
    @all_topic_posts = Post.search(params[:search])
    @current_page_posts = PostsUtils.posts_sort(@all_topic_posts.page(params[:page]), params[:order])
    @topics = Post.topics
  end

  # GET /posts/1 or /posts/1.json
  def show
    @topics = Post.topics
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    puts @post
    respond_to do |format|
      if @post.update(post_params) and @post.edit
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    Notification.where(second_target_id: @post.id).delete_all
    Reply.where(post_id: @post.id).delete_all
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:user_id, :topic, :title, :body, :create_at)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def get_topic_in_display_format(topic)
    topic.capitalize.gsub(/[^0-9A-Za-z]/, ' ')
  end

  def not_all_posts_are_displayed
    @all_topic_posts.length < @all_posts.length && !@current_page_posts.all.empty?
  end

  def no_posts_in_this_topic
    @current_page_posts.first.nil?
  end

  def get_current_topic
    get_topic_in_display_format(@topics.keys[@current_page_posts.first.topic])
  end

  def get_topic_from_id(topic_id)
    get_topic_in_display_format(Post.topics.keys[topic_id])
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h4 class="text-danger"><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul class="list-group">
        <% post.errors.full_messages.each do |message| %>
          <li class="list-group-item list-group-item-danger"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id.to_i%>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :topic %>
    <%= form.select(:topic, options_for_select(Post.topics.keys.map{|key| [key.capitalize.gsub(/[^0-9A-Za-z]/, ' '), Post.topics[key]]}), {:include_blank => "Select a topic", :selected => post.topic}, {:class => 'form-control'})%>
  </div>

  <%= form.submit "Save Post", class: 'btn text-light',  style: "background-color: #537A5A"  %>
<% end %>

app/views/posts/_reply.html.erb
<div class="card mt-3" style="box-shadow: 0px 4px 10px grey; background-color: #BAE7AC; border-radius: 20px;">
  <div class="card-body">
    <div class="button-right-up">
      <% if reply.user.id.to_i == current_user.id.to_i %>
        <%= link_to 'Edit', edit_reply_path(reply), class: 'btn btn-warning mx-1 text-dark'%>
      <% end %>
    </div>
    <p class="font-weight-bold"><%= reply.user.username%> | <%= reply.created_at%></p>
      
    <%= reply.body %>
    <div class="button-right">
    <%= link_to 'Dislikes', "#", class: 'btn btn-info text-white ' %> 3
  </div>
  <div class="button-right">
    <%= link_to 'Likes', "#", class: 'btn btn-info text-white ' %> 3
  </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="card my-5 bg" style="box-shadow: 0px 4px 10px grey; border: 5px solid green; border-radius: 25px;">
  <div class="card-body" >
    <h1>Edit Post</h1>

    <%= render 'form', post: @post %>

    <div class="mt-2">
      <%= link_to 'Remove', @post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger mr-2 text-light' %>
    </div>
    <div class="mt-2">
      <%= link_to 'Back', @post, class: 'btn btn-success mr-2 text-light' %>
    </div>
  </div>
</div>

<div style="height:150px;"> </div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <h2 class="col-2" style="padding: 10px;">
    <%= link_to "Topics:", posts_path, class: " text-dark space", style: "font-size: 35px;" %>
  </h2>
  <div class="scrolling-wrapper col-10 col-md-10 py-1 rounded" >
    <% @topics.each do |topic, key| %>
      <%= form_tag posts_path, :class=>"badge", :method => 'get' do %>
        <%= hidden_field_tag :search, key%>
        <%= hidden_field_tag :order, @current_order%>
        <%= submit_tag(get_topic_in_display_format(topic), :class=>"btn bg-success mr-2 px-5 text-light") %>
      <% end %>
    <% end %>
  </div>
</div>
<br>

<div class="row">
  <div class="col-6">
      <div class="dropdown ">

        <button id="sort-button" class="rounded dropbtn " style="margin: auto;width: 20%;border: 3px solid green;padding: 10px;">
          Sort By 
        </button>

        <div id="myDropdown" class="rounded dropdown-content">
          <% @orders.each do |order| %>
            <%= form_tag posts_path, :method => 'get' do %>
              <%= hidden_field_tag :order, order%>
              <% if @current_topic %>
                <%= hidden_field_tag :search, @current_topic %>
              <% end %>
              <%= submit_tag(order, class: "dropdown-content-button") %>
            <% end %>
          <% end %>
        </div>
      <a class='pl-3 text-muted'> Currently sorting by <%= @current_order %> </a>
      </div>
  </div>
  <div class="col-6">

    <% if not_all_posts_are_displayed %>
      <h1 class="text-dark p-right" >
        Posts about: 
        <i><%= link_to get_current_topic, posts_path, style: "color: #537A5A" %></i>
        <i class="fa fa-tree" style="color:green;" aria-hidden="true"></i>
      </h1>
    <% elsif no_posts_in_this_topic %>
      <h4 class="text-danger " style="text-align: right;">No posts were found for this topic!</h4>
    <% else %>
      <h1 class="text-warning " style="text-align: right;"><%= link_to "All Posts", posts_path %></h1>
    <% end %>
  </div>
</div>


<hr>


<%= link_to 'New Post', new_post_path, class: 'btn btn-secondary text-light' %>

<div class= "mb-5">

  <% @current_page_posts.each do |post| %>
    <div class="card mt-3" style="box-shadow: 0px 4px 10px grey; background: white">
      <div class="card-body">
        <h5 class="card-title"><%= link_to post.title, post_path(post) %></h5>
        <p class="card-text font-weight-bold">
            <%= post.user.username %>
          | <%= post.created_at %>
          | <%= post.replies.length %> Replies
          <%= "| Edited" if post.edited?%>
        </p>
        <% if post.user.id == current_user.id %>
          <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning text-dark' %>
        <% end %>
      </div>
    </div>
  <% end %>
  
</div>

<%= paginate @current_page_posts %>



<div class="post-bottom"></div>
<%if @current_page_posts.first.nil? %>
  <div class="post-bottom-2"></div>
<%end%>

<%= javascript_pack_tag 'post_button' %>

app/views/posts/new.html.erb
<div class="card my-5 bg" style="box-shadow: 0px 4px 10px grey; border: 5px solid green; border-radius: 25px;">
  <div class="card-body">
    <h1>New Post</h1>

    <%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path, class: 'btn btn-dark text-light mt-2' %>
  </div>
</div>

<div style="height:250px;"> </div>

app/views/posts/show.html.erb
<div class="card mt-5 mb-4" style="box-shadow: 0px 10px 10px grey; background-color: white; border-radius: 20px;">
  <div class="card-body">
    <%= link_to 'Back', posts_path, class: 'btn btn-dark text-light mr-1' %>
    <% if @post.user.id == current_user.id %>
      <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning mx-1 text-dark' %>
    <% end %>
    <%= form_tag posts_path, :class=>"badge", :method => 'get' do %>
      <%= hidden_field_tag :search, @post.topic%>
      <%= submit_tag(get_topic_from_id(@post.topic), :class=>"btn bg-success px-5 text-light") %>
    <% end %>
    
    <p class="ml-3" id="notice"><%= notice %></p>

    <h1 class="text-center"><%= @post.title %></h1>
    <hr>
    <div class="font-weight-bold">
        <%= @post.user.username %>
      | <%= @post.created_at %>
      | <%= @post.replies.length %> Replies
      <%= "| edited at: #{@post.edited_at}" if @post.edited?%>
    </div>
    <div class="my-4">
      <%= @post.body %>
    </div>
    
  </div>
</div>
<% if @post.replies.any? %>

  <% @post.replies.each do |reply| %>
  <div class="card mt-3" style="box-shadow: 0px 4px 10px grey; background-color: #A8A8A8; border-radius: 20px;">
    <div class="card-body">
      <div class="button-right-up">
        <% if reply.user.id == current_user.id %>
          <%= link_to 'Edit', edit_reply_path(reply), class: 'btn btn-warning mx-1 text-dark'%>
        <% end %>
      </div>
      <p class="font-weight-bold"><%= reply.user.username%> | <%= reply.created_at%></p>
        
      <%= reply.body %>
    </div>
  </div>
  <% end %>
<% end %>

<div class="card mt-3 mb-5 text-light" style="box-shadow: 0px 4px 10px grey; background-color: #A8A8A8	">
  <div class="card-body" >
    <p class="font-weight-bold" style="font-size: 20px;">New comment</p>
    <%= form_with(model: [@post, @post.replies.build]) do |form| %>
      <div class="form-group">
        <%= form.hidden_field :user_id, value: current_user.id.to_i%>
        <%= form.label 'Write your comment below' %>
        <%= form.text_area :body, class: 'form-control' %>
      </div>
      <%= form.submit 'Post Reply', class: 'btn text-light',  style: "background-color: #537A5A"  %>
    <% end %>
  </div>
</div>

<div style="height:150px;"> </div>