config/routes.rb
Rails.application.routes.draw do
  mount Notifications::Engine => "/notifications"
  resources :store_locators
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  
  resources :chatbot_steps
  
  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  resources :posts
  resources :posts do
    resources :replies, only: [:index, :create]
  end
  resources :replies, only: [:edit, :show, :update]
  resources :chatbot_messages, except: [:edit, :update, :destroy]
  resources :reminders
  resources :user_plants, except: [:index]
  resources :users, except: [:index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  constraints Clearance::Constraints::SignedIn.new do
    get '/', to: 'users#current_user_dashboard'
  end
  
  constraints Clearance::Constraints::SignedOut.new do
    get '/', to: redirect('/sign_in')
  end
end

app/controllers/chatbot_steps_controller.rb
require './lib/symptom_accessor'
require 'json'

class ChatbotStepsController < ApplicationController
  before_action :require_login
  before_action :set_shared_vars

  include Wicked::Wizard

  steps :choose_visit_type, :choose_plant, :select_symptoms, :answer_symptoms_questions, :display_possible_treatments # MORE STEPS GO HERE!
    
  def set_shared_vars
    @user = current_user
    @plant 
    @symptoms 
    @question 
    @symptom_assessor
    @symptom_causes
    @user_plants = UserPlant.where(user_id: current_user.id)
    @possible_treatments = []
  end
  
  def show
    case step
    when :choose_visit_type
      @prompt = "Please choose your visit type."
    when :choose_plant
      @bot_message = ChatbotMessage.create(user_id: current_user.id,
        time_sent: Time.now.utc,
        from_bot: true,
        content: "Please choose your visit type.")
      @prompt = "Which plant do you want to check in today?"
      @user_message = ChatbotMessage.create(user_id: current_user.id,
        time_sent: Time.now.utc,
        from_bot: false,
        content: "Symptom assessment")
      @bot_message = ChatbotMessage.create(user_id: current_user.id,
        time_sent: Time.now.utc,
        from_bot: true,
        content: @prompt)
    when :select_symptoms
      jump_to(:choose_plant)
    when :answer_symptoms_questions
      jump_to(:choose_plant)
    when :display_possible_treatments
      if params[:possible_treatments]
        @possible_treatments = params[:possible_treatments]
      else
        @possible_treatments = "No possible treatments found. Feel free to ask about this in a forum!"
      end
      @prompt = "Below are some possible treatments:"
      @bot_message = ChatbotMessage.create(user_id: current_user.id,
        time_sent: Time.now.utc,
        from_bot: true,
        content: "#{@prompt}\n#{@possible_treatments}")
    end

    render_wizard

  end

  def update
    @question_number = 0
    @possible_treatments = []
    case step
    when :select_symptoms
      @plant = UserPlant.where(user_id: current_user.id, id: params[:plant_id].to_i).first
      @symptom_assessor = SymptomAssessor.new(@plant.plant_type)
      @symptoms = @symptom_assessor.get_symptom_select_options
      @prompt = "What symptom does #{@plant.name.titleize} have?"
      @user_message = ChatbotMessage.create(user_id: current_user.id,
        time_sent: Time.now.utc,
        from_bot: false,
        content: params[:content])
      @bot_message = ChatbotMessage.create(user_id: current_user.id,
        time_sent: Time.now.utc,
        from_bot: true,
        content: @prompt)
    when :answer_symptoms_questions
      @plant = UserPlant.where(user_id: current_user.id, id: params[:plant_id].to_i).first
      @symptom_assessor = SymptomAssessor.new(@plant.plant_type)
      @symptom_id = params[:symptom_id].to_i
      @symptom_causes = @symptom_assessor.get_symptom_causes(@symptom_id)
      
      if params[:question_number]
        @question_number = params[:question_number].to_i 
      else
        @question_number = 0
      end

      if params[:possible_treatments]
        @possible_treatments = JSON.parse(params[:possible_treatments])
      else
        @possible_treatments = []
      end

      if params[:symptom_question_response]
        diagnosis = @symptom_assessor.get_diagnosis(@plant.plant_type,@symptom_id,@question_number-1, params[:symptom_question_response].to_i)
        if diagnosis
          @possible_treatments.append(diagnosis)
        end
      end

      if @question_number < @symptom_causes.length
        @question = @symptom_assessor.get_question_using_cause(@symptom_causes[@question_number])
        if !@question
          if @possible_treatments.empty?
            diagnosis = @symptom_assessor.get_questionless_diagnosis(@symptom_id,@question_number)
            @possible_treatments.append(diagnosis)
          end
          jump_to(:display_possible_treatments, possible_treatments: @possible_treatments)
        end
        @question_number += 1
      else
        jump_to(:display_possible_treatments, possible_treatments: @possible_treatments)
      end
      if params[:content]
        @user_message = ChatbotMessage.create(user_id: current_user.id,
          time_sent: Time.now.utc,
          from_bot: false,
          content: params[:content])
      end
      @user_message = ChatbotMessage.create(user_id: current_user.id,
        time_sent: Time.now.utc,
        from_bot: false,
        content: params[:symptom_question_response])
      @bot_message = ChatbotMessage.create(user_id: current_user.id,
        time_sent: Time.now.utc,
        from_bot: true,
        content: @question)
    end
    render_wizard
  end

  def new
    @chatbot_message = ChatbotMessage.new
  end

end

app/views/chatbot_steps/answer_symptoms_questions.html.erb
<div class="row" style="height: 100px;"> </div>

<div class="row bg-white" style="border-radius: 50px; text-align: center; height: 350px; border: 3px solid green; " >
  <div class="col vertical-center" style="padding: 20px;">
    <%= button_to 'Restart', wizard_path(:choose_visit_type), {class: "btn btn-dark btn-sm", method: "get"}%>
  </div>
  <div class="col-9 pb-5 bg-r-plant" style="text-shadow: 2px 2px yellow;">
    <h2 class="text-center p-4">
      <%= @question %>
    </h2>
    <!-- Buttons take to the next step (check steps over at app/controllers/chatbot_steps_controller.rb) -->
    <%= form_with(model: @chatbot_message,url: wizard_path, method: :put) do |form| %>
        <%= form.hidden_field :user_id, value: current_user.id.to_i %>
        <%= form.hidden_field :time_sent, value: Time.now.utc %>
        <%= form.hidden_field :from_bot, value: false %>
        <%= form.hidden_field :symptom_id, value: @symptom_id %>
        <%= form.hidden_field :plant_id, value: @plant.id %>
        <%= form.hidden_field :question_number, value: @question_number%>
        <%= form.hidden_field :possible_treatments, value: @possible_treatments.to_s%>
        <%= form.text_field :symptom_question_response%>
        <%= form.submit "Submit", class: "mt-2 btn text-light",  style: "background-color: #537A5A" %>
    <% end %>
  </div>
  <div class="col"></div>
</div>

 <div style="height: 500px"></div>

app/views/chatbot_steps/choose_plant.html.erb
<div class="row" style="height: 100px;"> </div>
<div class="row bg-white" style="border-radius: 50px; text-align: center; height: 350px;border: 3px solid green;" >

  <div class="col vertical-center" style="padding: 20px;">
      <%= button_to 'Restart', wizard_path(:choose_visit_type), {class: "btn btn-dark btn-sm", method: "get"}%>
  </div>
    <div class="col-8 bg-r-plant container" >
      <div class="row">
      <h2 class=" p-4" style="text-shadow: 2px 2px yellow; text-align: center;">
        Which plant do you want to check in today?
      </h2>
      </div>
      <div class="row col button-group">
      <!-- Buttons take to the next step (check steps over at app/controllers/chatbot_steps_controller.rb) -->
        <% @user_plants.each do |option| %>
        
          <%= form_with(model: @chatbot_message,url: next_wizard_path, method: :put) do |form| %>
            <%= form.hidden_field :user_id, value: current_user.id.to_i %>
            <%= form.hidden_field :time_sent, value: Time.now.utc %>
            <%= form.hidden_field :from_bot, value: false %>
            <%= form.hidden_field :plant_id, value: option.id %>
            <%= form.hidden_field :content, value: option.name%>
            <%= form.submit option.name, class: "mt-2 btn text-light button-group", 
            style: "padding-right:10px; padding-left: 10px;display: flex;margin: 0 5px; background-color: #537A5A" %>
          <% end %>
        <% end %>
        <br>
      </div>
      <div class="row" style="height:40px;"></div>
      <div class="row col-md-10">
        <%= link_to 'Add new plant', new_user_plant_path, class: "mt-2 btn btn-secondary text-light", 
        style: "position: absolute; top: 60%; left: 50%;"  %>
      </div>
    </div>
    <div class="col"></div>
</div>

 <div style="height: 500px"></div>

app/views/chatbot_steps/choose_visit_type.html.erb
<div class="row" style="height: 100px;"> </div>

<div class="row bg-white" style="border-radius: 50px; text-align: center; height: 350px; border: 3px solid green; " >

  <div class="col vertical-center " style="padding: 20px;">
    <%= button_to 'Restart', wizard_path(:choose_visit_type), {class: "btn btn-dark btn-sm", method: "get"}%>
  </div>

  <div class="col-9 pb-5 bg-r-plant">
    <h2 class="text-center p-4" style="text-shadow: 2px 2px yellow;">
      Hi, <%= current_user.username %>!
      <br>    
      <%= @prompt %>
    </h2>
    <!-- Buttons take to the next step (check steps over at app/controllers/chatbot_steps_controller.rb) -->
    <div class="row">
      <div class="col m-1">
        <%= button_to 'Symptom Assessment', wizard_path(:choose_plant), {class: "btn text-light btn-lg btn-block", method: "get", style: "background-color: #537A5A"}%>
      </div>
      <div class="col m-1">
        <%= button_to 'Check History', chatbot_messages_path, {class: "btn text-light btn-lg btn-block", method: "get", style: "background-color: #537A5A"} %>
      </div>
      <div class="col m-1">
        <!-- Replace :choose_plant with the correct path when you enable this button -->
        <%= button_to 'General Question', new_post_path, {class: "btn text-light btn-lg btn-block", method: "get", style: "background-color: #537A5A"} %>
      </div>
    </div>
  </div>
  <div class="col"></div>
</div>

 <div style="height: 500px"></div>

app/views/chatbot_steps/display_possible_treatments.html.erb
<div class="row" style="height: 100px;"> </div>

<div class="row bg-white" style="border-radius: 50px; text-align: center; height: 350px; border: 3px solid green; " >

  <div class="col vertical-center" style="padding: 20px;">
    <%= button_to 'Restart', wizard_path(:choose_visit_type), {class: "btn btn-dark btn-sm", method: "get"}%>
  </div>

  <div class="col-9 pb-5 bg-r-plant">
    <h2 class="text-center p-4" style="text-shadow: 2px 2px yellow;">
      <%= @prompt %>
    </h2>
    <!-- Buttons take to the next step (check steps over at app/controllers/chatbot_steps_controller.rb) -->
    <% @possible_treatments.each do |treatment| %>
      <div class=" rounded p-2 m-3 text-light" style= "background-color: #537A5A" >
        <%= treatment %>
      </div>
    <% end %>
  </div>

  <div class="col"></div>
</div>

 <div style="height: 500px"></div>

app/views/chatbot_steps/select_symptoms.html.erb
<div class="row" style="height: 100px;"> </div>

  
<div class="row bg-white" style="border-radius: 50px; text-align: center; height: 350px; border: 3px solid green; " >
 <div class="col vertical-center" style="padding: 20px;">
    <%= button_to 'Restart', wizard_path(:choose_visit_type), {class: "btn btn-dark btn-sm", method: "get"}%>
  </div>

  <div class="col-9 pb-5 bg-r-plant">
    <h2 class="text-center p-4" style="text-shadow: 2px 2px yellow;">
      <%= @prompt %>
    </h2>
    <!-- Buttons take to the next step (check steps over at app/controllers/chatbot_steps_controller.rb) -->
    <% @symptoms.each do |symptom| %>
      <%= form_with(model: @chatbot_message,url: next_wizard_path, method: :put) do |form| %>
        <%= form.hidden_field :user_id, value: current_user.id.to_i %>
        <%= form.hidden_field :time_sent, value: Time.now.utc %>
        <%= form.hidden_field :from_bot, value: false %>
        <%= form.hidden_field :symptom_id, value: symptom[1] %>
        <%= form.hidden_field :plant_id, value: @plant.id %>
        <%= form.hidden_field :content, value: symptom[0]%>
        <%= form.submit symptom[0], class: "mt-2 btn text-light",  style: "background-color: #537A5A" %>
      <% end %>
    <% end %>
  </div>
  <div class="col"></div>
</div>

 <div style="height: 500px"></div>